import { lstat, mkdir, readdir, rename, rm, rmdir, writeFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import create, { projectManifest } from '../../commands/create.mjs';
import { checkProject, withFsErrors } from '../../commands/validate.mjs';
import { NAME_PATTERN, PROJECT_MANIFEST, validateManifest } from '../manifest-reader.mjs';
import { inspectProject, readRegular } from '../project-package.mjs';
import { AgentError } from './errors.mjs';
import { admitArtifactPath } from './gates.mjs';

/*
 * Generated projects are assembled in <state>/runs/<id>/staging/<name> starting from the real
 * `zukujs create` scaffold, validated with the same checkProject/zwf admission as `validate`,
 * and only then moved into a freshly claimed <cwd>/<name> directory with one rename.
 * Existing projects are never overwritten.
 */
const NOFOLLOW = constants.O_NOFOLLOW ?? 0;
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
export const VENDOR_PHASER = 'src/vendor/phaser.min.js';
export const VENDOR_PHASER_LICENSE = 'src/vendor/phaser-LICENSE.txt';

export function deriveName(title, fallback) {
  const slug = String(title).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40).replace(/-+$/, '');
  return NAME_PATTERN.test(slug) ? slug : fallback;
}

export async function assertAbsent(path) {
  try { await lstat(path); } catch (error) {
    if (error?.code === 'ENOENT') return;
    throw new AgentError('AGENT_PROJECT_EXISTS');
  }
  throw new AgentError('AGENT_PROJECT_EXISTS');
}

/** Claims <cwd>/<name> with a non-recursive mkdir (atomic EEXIST). */
export async function claimProject(cwd, name) {
  if (!NAME_PATTERN.test(name)) throw new AgentError('INVALID_INPUT');
  const path = resolve(cwd, name);
  try { await mkdir(path, { mode: 0o755 }); } catch { throw new AgentError('AGENT_PROJECT_EXISTS'); }
  const stat = await lstat(path);
  return { path, name, dev: stat.dev, ino: stat.ino };
}

/** Removes the claim only while it is still our own empty directory. */
export async function releaseClaim(claim) {
  try {
    const stat = await lstat(claim.path);
    if (stat.isDirectory() && stat.ino === claim.ino && stat.dev === claim.dev && !(await readdir(claim.path)).length) await rmdir(claim.path);
  } catch { /* nothing to release */ }
}

/** Builds the zukujs.json for a generated game from the create() defaults. */
export function buildManifest(name, plan, meta) {
  const manifest = projectManifest(name);
  manifest.title = (meta?.title ?? plan.title).trim();
  manifest.description = meta?.description ?? plan.summary.slice(0, 500);
  manifest.tags = meta?.tags ?? [];
  manifest.age_rating = meta?.age_rating ?? 'all';
  manifest.jump.genre = meta?.genre ?? plan.genre;
  manifest.jump.platform = meta?.platform ?? { pc: true, mobile: false, tablet: false };
  if (validateManifest(manifest).length) throw new AgentError('AGENT_GATE_FAILED', { codes: ['MANIFEST_INVALID'] });
  return manifest;
}

const readme = (manifest, plan, engine) => `# ${manifest.title}\n\n${plan.summary}\n\nGenerated by the ZukuJS local game agent. All game files are editable under \`src/\`.\n\n## Controls\n\n${plan.input_actions.map(action => `- ${action.id}: ${action.keys.join(', ')}${action.pointer ? ' (pointer)' : ''}`).join('\n')}\n\n## Engine\n\n${engine.name}${engine.version ? ` ${engine.version}` : ''} — ${engine.reason}\n\n## Commands\n\n\`\`\`sh\nzukujs validate .\nzukujs package .\n\`\`\`\n`;

async function writeInside(root, relative, content) {
  const parts = relative.split('/');
  let dir = root;
  for (const part of parts.slice(0, -1)) {
    dir = join(dir, part);
    try { await mkdir(dir, { mode: 0o755 }); } catch (error) { if (error?.code !== 'EEXIST') throw error; }
    const stat = await lstat(dir);
    if (stat.isSymbolicLink() || !stat.isDirectory()) throw new AgentError('AGENT_ARTIFACT_UNSAFE');
  }
  await writeFile(join(root, relative), content, { flag: constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | NOFOLLOW, mode: 0o644 });
}

/**
 * Writes a fresh staging project: create() scaffold, generated src files, CLI-owned engine bundle,
 * manifest and README. Any previous staging content for this run is removed first.
 */
export async function stageProject({ runDir, name, manifest, plan, engine, files }) {
  const staging = join(runDir, 'staging');
  await rm(staging, { recursive: true, force: true });
  await mkdir(staging, { mode: 0o700 });
  await create([name], { cwd: staging });
  const root = join(staging, name);
  // The scaffold's own game is replaced by the generated files (its source was model input when chosen).
  await rm(join(root, 'src'), { recursive: true, force: true });
  await mkdir(join(root, 'src'), { mode: 0o755 });
  await writeFile(join(root, PROJECT_MANIFEST), JSON.stringify(manifest, null, 2) + '\n', { mode: 0o644 });
  await writeFile(join(root, 'README.md'), readme(manifest, plan, engine), { mode: 0o644 });
  for (const file of files) {
    if (admitArtifactPath(file.path) !== file.path) throw new AgentError('AGENT_ARTIFACT_UNSAFE');
    await writeInside(root, file.path, file.content);
  }
  if (engine.name === 'phaser') {
    await writeInside(root, VENDOR_PHASER, engine.bytes);
    if (engine.license) await writeInside(root, VENDOR_PHASER_LICENSE, engine.license);
  }
  return root;
}

export async function rewriteManifest(root, manifest) {
  await writeFile(join(root, PROJECT_MANIFEST), JSON.stringify(manifest, null, 2) + '\n', { flag: constants.O_WRONLY | constants.O_TRUNC | NOFOLLOW });
}

const digestOf = entries => sha256(entries.map(([path, bytes]) => `${path}\0${sha256(bytes)}\n`).join(''));

/**
 * Validates the project exactly like `zukujs validate`, then reads the packaged source bytes once.
 * The returned snapshot is what the browser serves and what the publish gate compares.
 */
export async function snapshotProject(root, signal) {
  return withFsErrors(async () => {
    const { project, result } = await checkProject(root, undefined, () => Boolean(signal?.aborted));
    const { report, files } = await inspectProject(root);
    if (!report.valid) throw new AgentError('AGENT_SOURCE_CHANGED');
    const source = new Map();
    for (const file of files) {
      const read = await readRegular(join(root, project.source, file.name), file);
      if (!read.bytes) throw new AgentError('AGENT_SOURCE_CHANGED');
      source.set(file.name, read.bytes);
    }
    const manifest = await readRegular(join(root, PROJECT_MANIFEST), undefined, 64 * 1024);
    if (!manifest.bytes) throw new AgentError('AGENT_SOURCE_CHANGED');
    const entries = [...source].sort(([a], [b]) => Buffer.compare(Buffer.from(a), Buffer.from(b)));
    const srcDigest = digestOf(entries);
    const fullDigest = digestOf([[PROJECT_MANIFEST, manifest.bytes], ...entries.map(([path, bytes]) => [`${project.source}/${path}`, bytes])]);
    // Same deterministic bytes `zukujs package` writes for the manifest's default format.
    return { root, project, files: source, entry: project.entry, srcDigest, fullDigest, packageSha256: sha256(result.bytes) };
  });
}

/** Moves the validated staging project onto the still-empty claimed directory. */
export async function materialize(stagingRoot, claim) {
  const stat = await lstat(claim.path).catch(() => undefined);
  if (!stat || !stat.isDirectory() || stat.ino !== claim.ino || stat.dev !== claim.dev || (await readdir(claim.path)).length) throw new AgentError('AGENT_PROJECT_EXISTS');
  try { await rename(stagingRoot, claim.path); } catch (error) {
    if (process.platform === 'win32' && ['EPERM', 'EEXIST', 'EACCES'].includes(error?.code)) {
      await rmdir(claim.path);
      await rename(stagingRoot, claim.path);
    } else throw new AgentError(error?.code === 'ENOTEMPTY' || error?.code === 'EEXIST' ? 'AGENT_PROJECT_EXISTS' : 'COMMAND_FAILED');
  }
  await rm(dirname(stagingRoot), { recursive: true, force: true }).catch(() => {});
  return claim.path;
}
